rsi <- rep(NA,182)

quantmod::getSymbols("AAL")
rsi[1] <- tail(myRSI14(Cl(AAL)),1)
quantmod::getSymbols("AAPL")
rsi[2] <- tail(myRSI14(Cl(AAPL)),1)
quantmod::getSymbols("ABNB")
rsi[3] <- tail(myRSI14(Cl(ABNB)),1)
quantmod::getSymbols("ACN")
rsi[4] <- tail(myRSI14(Cl(ACN)),1)
quantmod::getSymbols("ADBE")
rsi[5] <- tail(myRSI14(Cl(ADBE)),1)
quantmod::getSymbols("AIG")
rsi[6] <- tail(myRSI14(Cl(AIG)),1)
quantmod::getSymbols("AMD")
rsi[7] <- tail(myRSI14(Cl(AMD)),1)
quantmod::getSymbols("AMZN")
rsi[8] <- tail(myRSI14(Cl(AMZN)),1)
quantmod::getSymbols("ANF")
rsi[9] <- tail(myRSI14(Cl(ANF)),1)
quantmod::getSymbols("AXP")
rsi[10] <- tail(myRSI14(Cl(AXP)),1)
quantmod::getSymbols("B")
rsi[11] <- tail(myRSI14(Cl(B)),1)
quantmod::getSymbols("BA")
rsi[12] <- tail(myRSI14(Cl(BA)),1)
quantmod::getSymbols("BABA")
rsi[13] <- tail(myRSI14(Cl(BABA)),1)
quantmod::getSymbols("BAC")
rsi[14] <- tail(myRSI14(Cl(BAC)),1)
quantmod::getSymbols("BB")
rsi[15] <- tail(myRSI14(Cl(BB)),1)
quantmod::getSymbols("BCS")
rsi[16] <- tail(myRSI14(Cl(BCS)),1)
quantmod::getSymbols("BIDU")
rsi[17] <- tail(myRSI14(Cl(BIDU)),1)
quantmod::getSymbols("BIIB")
rsi[18] <- tail(myRSI14(Cl(BIIB)),1)
quantmod::getSymbols("BIOX")
rsi[19] <- tail(myRSI14(Cl(BIOX)),1)
quantmod::getSymbols("BITF")
rsi[20] <- tail(myRSI14(Cl(BITF)),1)
quantmod::getSymbols("C")
rsi[21] <- tail(myRSI14(Cl(C)),1)
quantmod::getSymbols("CAT")
rsi[22] <- tail(myRSI14(Cl(CAT)),1)
quantmod::getSymbols("CL")
rsi[23] <- tail(myRSI14(Cl(CL)),1)
quantmod::getSymbols("CLS")
rsi[24] <- tail(myRSI14(Cl(CLS)),1)
quantmod::getSymbols("COIN")
rsi[25] <- tail(myRSI14(Cl(COIN)),1)
quantmod::getSymbols("COST")
rsi[26] <- tail(myRSI14(Cl(COST)),1)
quantmod::getSymbols("CRM")
rsi[27] <- tail(myRSI14(Cl(CRM)),1)
quantmod::getSymbols("CSCO")
rsi[28] <- tail(myRSI14(Cl(CSCO)),1)
quantmod::getSymbols("CVX")
rsi[29] <- tail(myRSI14(Cl(CVX)),1)
quantmod::getSymbols("CX")
rsi[30] <- tail(myRSI14(Cl(CX)),1)
quantmod::getSymbols("DD")
rsi[31] <- tail(myRSI14(Cl(DD)),1)
quantmod::getSymbols("DE")
rsi[32] <- tail(myRSI14(Cl(DE)),1)
quantmod::getSymbols("DECK")
rsi[33] <- tail(myRSI14(Cl(DECK)),1)
quantmod::getSymbols("DEO")
rsi[34] <- tail(myRSI14(Cl(DEO)),1)
quantmod::getSymbols("DIA")
rsi[35] <- tail(myRSI14(Cl(DIA)),1)
quantmod::getSymbols("DOCU")
rsi[36] <- tail(myRSI14(Cl(DOCU)),1)
quantmod::getSymbols("DOW")
rsi[37] <- tail(myRSI14(Cl(DOW)),1)
quantmod::getSymbols("E")
rsi[38] <- tail(myRSI14(Cl(E)),1)
quantmod::getSymbols("EA")
rsi[39] <- tail(myRSI14(Cl(EA)),1)
quantmod::getSymbols("EBAY")
rsi[40] <- tail(myRSI14(Cl(EBAY)),1)
quantmod::getSymbols("EEM")
rsi[41] <- tail(myRSI14(Cl(EEM)),1)
quantmod::getSymbols("EFX")
rsi[42] <- tail(myRSI14(Cl(EFX)),1)
quantmod::getSymbols("ERIC")
rsi[43] <- tail(myRSI14(Cl(ERIC)),1)
quantmod::getSymbols("ETHA")
rsi[44] <- tail(myRSI14(Cl(ETHA)),1)
quantmod::getSymbols("EWZ")
rsi[45] <- tail(myRSI14(Cl(EWZ)),1)
quantmod::getSymbols("F")
rsi[46] <- tail(myRSI14(Cl(F)),1)
quantmod::getSymbols("FCX")
rsi[47] <- tail(myRSI14(Cl(FCX)),1)
quantmod::getSymbols("FDX")
rsi[48] <- tail(myRSI14(Cl(FDX)),1)
quantmod::getSymbols("FMCC")
rsi[49] <- tail(myRSI14(Cl(FMCC)),1)
quantmod::getSymbols("FMX")
rsi[50] <- tail(myRSI14(Cl(FMX)),1)
quantmod::getSymbols("FNMA")
rsi[51] <- tail(myRSI14(Cl(FNMA)),1)
quantmod::getSymbols("FSLR")
rsi[52] <- tail(myRSI14(Cl(FSLR)),1)
quantmod::getSymbols("FXI") 
rsi[53] <- tail(myRSI14(Cl(FXI)),1)
quantmod::getSymbols("GE") 
rsi[54] <- tail(myRSI14(Cl(GE)),1)
quantmod::getSymbols("GGB") 
rsi[55] <- tail(myRSI14(Cl(GGB)),1)
quantmod::getSymbols("GLD") 
rsi[56] <- tail(myRSI14(Cl(GLD)),1)
quantmod::getSymbols("GLOB") 
rsi[57] <- tail(myRSI14(Cl(GLOB)),1)
quantmod::getSymbols("GM") 
rsi[58] <- tail(myRSI14(Cl(GM)),1)
quantmod::getSymbols("GOOGL") 
rsi[59] <- tail(myRSI14(Cl(GOOGL)),1)
quantmod::getSymbols("GPRK") 
rsi[60] <- tail(myRSI14(Cl(GPRK)),1)
quantmod::getSymbols("GRMN") 
rsi[61] <- tail(myRSI14(Cl(GRMN)),1)
quantmod::getSymbols("GS") 
rsi[62] <- tail(myRSI14(Cl(GS)),1)
quantmod::getSymbols("GSK") 
rsi[63] <- tail(myRSI14(Cl(GSK)),1)
quantmod::getSymbols("HAL") 
rsi[64] <- tail(myRSI14(Cl(HAL)),1)
quantmod::getSymbols("HD") 
rsi[65] <- tail(myRSI14(Cl(HD)),1)
quantmod::getSymbols("HDB") 
rsi[66] <- tail(myRSI14(Cl(HDB)),1)
quantmod::getSymbols("HMC") 
rsi[67] <- tail(myRSI14(Cl(HMC)),1)
quantmod::getSymbols("HOG") 
rsi[68] <- tail(myRSI14(Cl(HOG)),1)
quantmod::getSymbols("HON") 
rsi[69] <- tail(myRSI14(Cl(HON)),1)
quantmod::getSymbols("HPQ") 
rsi[70] <- tail(myRSI14(Cl(HPQ)),1)
quantmod::getSymbols("HSBC") 
rsi[71] <- tail(myRSI14(Cl(HSBC)),1)
quantmod::getSymbols("HSY") 
rsi[72] <- tail(myRSI14(Cl(HSY)),1)
quantmod::getSymbols("HUT") 
rsi[73] <- tail(myRSI14(Cl(HUT)),1)
quantmod::getSymbols("IBB") 
rsi[74] <- tail(myRSI14(Cl(IBB)),1)
quantmod::getSymbols("IBIT") 
rsi[75] <- tail(myRSI14(Cl(IBIT)),1)
quantmod::getSymbols("IBM") 
rsi[76] <- tail(myRSI14(Cl(IBM)),1)
quantmod::getSymbols("IEUR") 
rsi[77] <- tail(myRSI14(Cl(IEUR)),1)
quantmod::getSymbols("ING") 
rsi[78] <- tail(myRSI14(Cl(ING)),1)
quantmod::getSymbols("INTC") 
rsi[79] <- tail(myRSI14(Cl(INTC)),1)
quantmod::getSymbols("ITUB") 
rsi[80] <- tail(myRSI14(Cl(ITUB)),1)
quantmod::getSymbols("IVE") 
rsi[81] <- tail(myRSI14(Cl(IVE)),1)
quantmod::getSymbols("IVW") 
rsi[82] <- tail(myRSI14(Cl(IVW)),1)
quantmod::getSymbols("IWM") 
rsi[83] <- tail(myRSI14(Cl(IWM)),1)
quantmod::getSymbols("JCI") 
rsi[84] <- tail(myRSI14(Cl(JCI)),1)
quantmod::getSymbols("JD") 
rsi[85] <- tail(myRSI14(Cl(JD)),1)
quantmod::getSymbols("JMIA") 
rsi[86] <- tail(myRSI14(Cl(JMIA)),1)
quantmod::getSymbols("JNJ") 
rsi[87] <- tail(myRSI14(Cl(JNJ)),1)
quantmod::getSymbols("JPM") 
rsi[88] <- tail(myRSI14(Cl(JPM)),1)
quantmod::getSymbols("KB") 
rsi[89] <- tail(myRSI14(Cl(KB)),1)
quantmod::getSymbols("KEP") 
rsi[90] <- tail(myRSI14(Cl(KEP)),1)
quantmod::getSymbols("KGC") 
rsi[91] <- tail(myRSI14(Cl(KGC)),1)
quantmod::getSymbols("KMB") 
rsi[92] <- tail(myRSI14(Cl(KMB)),1)
quantmod::getSymbols("KO") 
rsi[93] <- tail(myRSI14(Cl(KO)),1)
quantmod::getSymbols("LAC") 
rsi[94] <- tail(myRSI14(Cl(LAC)),1)
quantmod::getSymbols("LLY") 
rsi[95] <- tail(myRSI14(Cl(LLY)),1)
quantmod::getSymbols("LMT") 
rsi[96] <- tail(myRSI14(Cl(LMT)),1)
quantmod::getSymbols("LRCX") 
rsi[97] <- tail(myRSI14(Cl(LRCX)),1)
quantmod::getSymbols("LVS") 
rsi[98] <- tail(myRSI14(Cl(LVS)),1)
quantmod::getSymbols("LYG") 
rsi[99] <- tail(myRSI14(Cl(LYG)),1)
quantmod::getSymbols("MA") 
rsi[100] <- tail(myRSI14(Cl(MA)),1)
quantmod::getSymbols("MCD") 
rsi[101] <- tail(myRSI14(Cl(MCD)),1)
quantmod::getSymbols("MELI") 
rsi[102] <- tail(myRSI14(Cl(MELI)),1)
quantmod::getSymbols("META") 
rsi[103] <- tail(myRSI14(Cl(META)),1)
quantmod::getSymbols("MMM") 
rsi[104] <- tail(myRSI14(Cl(MMM)),1)
quantmod::getSymbols("MO") 
rsi[105] <- tail(myRSI14(Cl(MO)),1)
quantmod::getSymbols("MRK") 
rsi[106] <- tail(myRSI14(Cl(MRK)),1)
quantmod::getSymbols("MSFT") 
rsi[107] <- tail(myRSI14(Cl(MSFT)),1)
quantmod::getSymbols("MSI") 
rsi[108] <- tail(myRSI14(Cl(MSI)),1)
quantmod::getSymbols("MSTR") 
rsi[109] <- tail(myRSI14(Cl(MSTR)),1)
quantmod::getSymbols("NEM") 
rsi[110] <- tail(myRSI14(Cl(NEM)),1)
quantmod::getSymbols("NFLX") 
rsi[111] <- tail(myRSI14(Cl(NFLX)),1)
quantmod::getSymbols("NG") 
rsi[112] <- tail(myRSI14(Cl(NG)),1)
quantmod::getSymbols("NGG") 
rsi[113] <- tail(myRSI14(Cl(NGG)),1)
quantmod::getSymbols("NIO") 
rsi[114] <- tail(myRSI14(Cl(NIO)),1)
quantmod::getSymbols("NKE") 
rsi[115] <- tail(myRSI14(Cl(NKE)),1)
quantmod::getSymbols("NMR") 
rsi[116] <- tail(myRSI14(Cl(NMR)),1)
quantmod::getSymbols("NU") 
rsi[117] <- tail(myRSI14(Cl(NU)),1)
quantmod::getSymbols("NVDA") 
rsi[118] <- tail(myRSI14(Cl(NVDA)),1)
quantmod::getSymbols("NVS") 
rsi[119] <- tail(myRSI14(Cl(NVS)),1)
quantmod::getSymbols("ORCL") 
rsi[120] <- tail(myRSI14(Cl(ORCL)),1)
quantmod::getSymbols("OXY") 
rsi[121] <- tail(myRSI14(Cl(OXY)),1)
quantmod::getSymbols("PAAS") 
rsi[122] <- tail(myRSI14(Cl(PAAS)),1)
quantmod::getSymbols("PAC") 
rsi[123] <- tail(myRSI14(Cl(PAC)),1)
quantmod::getSymbols("PAGS") 
rsi[124] <- tail(myRSI14(Cl(PAGS)),1)
quantmod::getSymbols("PANW") 
rsi[125] <- tail(myRSI14(Cl(PANW)),1)
quantmod::getSymbols("PBI") 
rsi[126] <- tail(myRSI14(Cl(PBI)),1)
quantmod::getSymbols("PBR") 
rsi[127] <- tail(myRSI14(Cl(PBR)),1)
quantmod::getSymbols("PEP") 
rsi[128] <- tail(myRSI14(Cl(PEP)),1)
quantmod::getSymbols("PFE") 
rsi[129] <- tail(myRSI14(Cl(PFE)),1)
quantmod::getSymbols("PG") 
rsi[130] <- tail(myRSI14(Cl(PG)),1)
quantmod::getSymbols("PYPL") 
rsi[131] <- tail(myRSI14(Cl(PYPL)),1)
quantmod::getSymbols("QCOM") 
rsi[132] <- tail(myRSI14(Cl(QCOM)),1)
quantmod::getSymbols("QQQ") 
rsi[133] <- tail(myRSI14(Cl(QQQ)),1)
quantmod::getSymbols("RBLX") 
rsi[134] <- tail(myRSI14(Cl(RBLX)),1)
quantmod::getSymbols("RGTI") 
rsi[135] <- tail(myRSI14(Cl(RGTI)),1)
quantmod::getSymbols("RIO") 
rsi[136] <- tail(myRSI14(Cl(RIO)),1)
quantmod::getSymbols("ROST") 
rsi[137] <- tail(myRSI14(Cl(ROST)),1)
quantmod::getSymbols("RTX") 
rsi[138] <- tail(myRSI14(Cl(RTX)),1)
quantmod::getSymbols("SAN") 
rsi[139] <- tail(myRSI14(Cl(SAN)),1)
quantmod::getSymbols("SAP") 
rsi[140] <- tail(myRSI14(Cl(SAP)),1)
quantmod::getSymbols("SATL") 
rsi[141] <- tail(myRSI14(Cl(SATL)),1)
quantmod::getSymbols("SBUX") 
rsi[142] <- tail(myRSI14(Cl(SBUX)),1)
quantmod::getSymbols("SH") 
rsi[143] <- tail(myRSI14(Cl(SH)),1)
quantmod::getSymbols("SHOP") 
rsi[144] <- tail(myRSI14(Cl(SHOP)),1)
quantmod::getSymbols("SONY") 
rsi[145] <- tail(myRSI14(Cl(SONY)),1)
quantmod::getSymbols("SPGI") 
rsi[146] <- tail(myRSI14(Cl(SPGI)),1)
quantmod::getSymbols("SPOT") 
rsi[147] <- tail(myRSI14(Cl(SPOT)),1)
quantmod::getSymbols("SPY") 
rsi[148] <- tail(myRSI14(Cl(SPY)),1)
quantmod::getSymbols("T") 
rsi[149] <- tail(myRSI14(Cl(T)),1)
quantmod::getSymbols("TEAM") 
rsi[150] <- tail(myRSI14(Cl(TEAM)),1)
quantmod::getSymbols("TEN") 
rsi[151] <- tail(myRSI14(Cl(TEN)),1)
quantmod::getSymbols("TGT") 
rsi[152] <- tail(myRSI14(Cl(TGT)),1)
quantmod::getSymbols("TM") 
rsi[153] <- tail(myRSI14(Cl(TM)),1)
quantmod::getSymbols("TRIP") 
rsi[154] <- tail(myRSI14(Cl(TRIP)),1)
quantmod::getSymbols("TSLA") 
rsi[155] <- tail(myRSI14(Cl(TSLA)),1)
quantmod::getSymbols("TSM") 
rsi[156] <- tail(myRSI14(Cl(TSM)),1)
quantmod::getSymbols("TWLO") 
rsi[157] <- tail(myRSI14(Cl(TWLO)),1)
quantmod::getSymbols("UAL") 
rsi[158] <- tail(myRSI14(Cl(UAL)),1)
quantmod::getSymbols("UBER") 
rsi[159] <- tail(myRSI14(Cl(UBER)),1)
quantmod::getSymbols("UGP") 
rsi[160] <- tail(myRSI14(Cl(UGP)),1)
quantmod::getSymbols("UL") 
rsi[161] <- tail(myRSI14(Cl(UL)),1)
quantmod::getSymbols("UNH") 
rsi[162] <- tail(myRSI14(Cl(UNH)),1)
quantmod::getSymbols("UNP") 
rsi[163] <- tail(myRSI14(Cl(UNP)),1)
quantmod::getSymbols("URBN") 
rsi[164] <- tail(myRSI14(Cl(URBN)),1)
quantmod::getSymbols("USB") 
rsi[165] <- tail(myRSI14(Cl(USB)),1)
quantmod::getSymbols("V") 
rsi[166] <- tail(myRSI14(Cl(V)),1)
quantmod::getSymbols("VALE") 
rsi[167] <- tail(myRSI14(Cl(VALE)),1)
quantmod::getSymbols("VEA") 
rsi[168] <- tail(myRSI14(Cl(VEA)),1)
quantmod::getSymbols("VIV") 
rsi[169] <- tail(myRSI14(Cl(VIV)),1)
quantmod::getSymbols("VIST") 
rsi[170] <- tail(myRSI14(Cl(VIST)),1)
quantmod::getSymbols("VOD") 
rsi[171] <- tail(myRSI14(Cl(VOD)),1)
quantmod::getSymbols("VRSN") 
rsi[172] <- tail(myRSI14(Cl(VRSN)),1)
quantmod::getSymbols("VRTX") 
rsi[173] <- tail(myRSI14(Cl(VRTX)),1)
quantmod::getSymbols("VST") 
rsi[174] <- tail(myRSI14(Cl(VST)),1)
quantmod::getSymbols("VZ") 
rsi[175] <- tail(myRSI14(Cl(VZ)),1)
quantmod::getSymbols("WFC") 
rsi[176] <- tail(myRSI14(Cl(WFC)),1)
quantmod::getSymbols("WMT") 
rsi[177] <- tail(myRSI14(Cl(WMT)),1)
quantmod::getSymbols("XOM") 
rsi[178] <- tail(myRSI14(Cl(XOM)),1)
quantmod::getSymbols("XP") 
rsi[179] <- tail(myRSI14(Cl(XP)),1)
quantmod::getSymbols("XYZ") 
rsi[180] <- tail(myRSI14(Cl(XYZ)),1)
quantmod::getSymbols("YELP") 
rsi[181] <- tail(myRSI14(Cl(YELP)),1)
quantmod::getSymbols("ZM") 
rsi[182] <- tail(myRSI14(Cl(ZM)),1)

nombres <- c("AAL","AAPL","ABNB","ACN","ADBE","AIG","AMD","AMZN","ANF","AXP",
             "B","BA","BABA","BAC","BB","BCS",'BIDU',"BIIB","BIOX","BITF","C",
             "CAT","CL","CLS","COIN","COST","CRM","CSCO","CVX","CX","DD","DE",
             "DECK","DEO","DIA","DOCU","DOW","E","EA","EBAY","EEM","EFX",
             "ERIC","ETHA","EWZ","F","FCX","FDX","FMCC","FMX","FNMA",
             "FSLR","FXI","GE","GGB","GLD","GLOB","GM","GOOGL","GPRK","GRMN",
             "GS","GSK","HAL","HD","HDB","HMC","HOG","HON","HPQ","HSBC","HSY",
             "HUT","IBB","IBIT","IBM","IEUR","ING","INTC","ITUB","IVE","IVW",
             "IWM","JCI","JD","JMIA","JNJ","JPM","KB","KEP","KGC","KMB","KO",
             "LAC","LLY","LMT","LRCX","LVS","LYG","MA","MCD","MELI","META",
             "MMM","MO","MRK","MSFT","MSI","MSTR","NEM","NFLX","NG","NGG","NIO",
             "NKE","NMR","NU","NVDA","NVS","ORCL","OXY","PAAS","PAC","PAGS",
             "PANW","PBI","PBR","PEP","PFE","PG","PYPL","QCOM","QQQ","RBLX",
             "RGTI","RIO","ROST","RTX","SAN","SAP","SATL","SBUX","SH","SHOP",
             "SONY","SPGI","SPOT","SPY","T","TEAM","TEN","TGT","TM",
             "TRIP","TSLA","TSM","TWLO","UBER","UAL","UGP","UL","UNH","UNP",
             "URBN","USB","V","VALE","VEA","VIV","VIST","VOD","VRSN","VRTX",
             "VST","VZ","WFC","WMT","XOM","XP","XYZ","YELP","ZM")

tabla <- as.data.frame(cbind(nombres,rsi))

filter(tabla,rsi<30)
filter(tabla,rsi>70)

